[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
private_vesting = "8UKRtLxSCUwCwXBTyAt3oqsDBy8gFinr2Cm4C1iPLp8Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/ledgerninja/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
